import unittest
import hebrew_converter

class TestTimes(unittest.TestCase):
    def test_convert_to_words(self):
        self.assertEqual(hebrew_converter.convert_to_words("5784", "1", "1"), "1 Nisan 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "2", "3"), "3 Iyar 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "3", "4"), "4 Sivan 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "4", "5"), "5 Tammuz 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "5", "6"), "6 Av 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "6", "7"), "7 Elul 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "7", "8"), "8 Tishrei 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "8", "9"), "9 Cheshvan 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "9", "10"), "10 Kislev 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "10", "11"), "11 Tevet 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "11", "12"), "12 Shevat 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "12", "13"), "13 Adar I 5784")
        self.assertEqual(hebrew_converter.convert_to_words("5785", "12", "13"), "13 Adar 5785")
        self.assertEqual(hebrew_converter.convert_to_words("5784", "13", "14"), "14 Adar II 5784")

    def test_calc_month_name(self):
        self.assertEqual(hebrew_converter.calc_month_name(5784, 1), "Nisan")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 2), "Iyar")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 3), "Sivan")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 4), "Tammuz")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 5), "Av")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 6), "Elul")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 7), "Tishrei")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 8), "Cheshvan")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 9), "Kislev")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 10), "Tevet")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 11), "Shevat")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 12), "Adar I")
        self.assertEqual(hebrew_converter.calc_month_name(5785, 12), "Adar")
        self.assertEqual(hebrew_converter.calc_month_name(5784, 13), "Adar II")


    def test_is_leap_year(self):
        self.assertTrue(hebrew_converter.is_leap_year(5784))
        self.assertFalse(hebrew_converter.is_leap_year(5785))
        self.assertFalse(hebrew_converter.is_leap_year(5786))
        self.assertTrue(hebrew_converter.is_leap_year(5787))
        self.assertFalse(hebrew_converter.is_leap_year(5788))
        self.assertFalse(hebrew_converter.is_leap_year(5789))
        self.assertTrue(hebrew_converter.is_leap_year(5790))
        self.assertFalse(hebrew_converter.is_leap_year(5791))
        self.assertFalse(hebrew_converter.is_leap_year(5792))
        self.assertTrue(hebrew_converter.is_leap_year(5793))
        self.assertFalse(hebrew_converter.is_leap_year(5794))
        self.assertTrue(hebrew_converter.is_leap_year(5795))
        self.assertFalse(hebrew_converter.is_leap_year(5796))
        self.assertFalse(hebrew_converter.is_leap_year(5797))
        self.assertTrue(hebrew_converter.is_leap_year(5798))
        self.assertFalse(hebrew_converter.is_leap_year(5799))
        self.assertFalse(hebrew_converter.is_leap_year(5800))
        self.assertTrue(hebrew_converter.is_leap_year(5801))
        self.assertFalse(hebrew_converter.is_leap_year(5802))
